### ISSUE TITLE
添加下 插件的keywords "translateSource" 可以在comment translate中搜索到

### ISSUE THREAD

**Issue by intellism** [zoooooway/comment-translate-caiyun#1]
![image](https://github.com/zoooooway/comment-translate-caiyun/assets/442894/7e6d8616-1f18-4989-8813-4f3946d4f697)

![image](https://github.com/zoooooway/comment-translate-caiyun/assets/442894/2edf2cdf-fb2a-498c-bfbd-ba06b24bd454)

![image](https://github.com/zoooooway/comment-translate-caiyun/assets/442894/36f8b5f2-8ab4-40e9-a5cc-31bc177169f4)

**Comment by zoooooway** [comment]
@intellism  已添加
